# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [130]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1, 2, 3]
l_2 = [4, 5, 6]

print(f"Summing of two lists: {l_1 + l_2}")
print(f"Difference of two lists: {l_1 - l_2}")

Summing of two lists: [1, 2, 3, 4, 5, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [4]:
def add_lists(list1, list2):
    list3 = []
    for index in range(len(list1)):
        list3.append(list1[index] + list2[index])
    return list3


add_lists([2, 3, 4], [1, 5, 2])
# [3, 8, 6]

[3, 8, 6]

#### Importing

In [5]:
# always import as np, standard across all of data science
# !pip install numpy
import numpy as np

In [6]:
np

<module 'numpy' from 'C:\\Users\\bstan\\anaconda3\\envs\\intro\\lib\\site-packages\\numpy\\__init__.py'>

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [7]:
arr1 = np.array([1., 2., 3.])

print(arr1)
print(type(arr1))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [8]:
arr1.dtype

dtype('float64')

###### - np.zeros()

In [9]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((5, 10)) # shape can be one number or a tuple of (rows, columns)

print(arr_zeros)
print(type(arr_zeros))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [10]:
arr_zeros

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

###### - np.ones()

In [11]:
arr_ones = np.ones((3, 7), int)
print(arr_ones)
print(arr_ones.dtype)
# notice no dots after the numbers, because we specified the datatype to be integer

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]
int32


In [12]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionadded:: 1.20

###### - np.arange()

In [13]:
arr_range = np.arange(5, 25, 5)
print(arr_range)

[ 5 10 15 20]


###### - Making Lists into NDArrays

In [14]:
list_1 = [3, 5, 7, 2, 4, 2]

arr_list = np.array(list_1)
arr_list

array([3, 5, 7, 2, 4, 2])

#### Performing Calculations on NDArrays

###### - Summation

In [15]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum

array([15, 30, 45, 60, 75])

###### - Difference

In [16]:
result_diff = arr_list2 - arr_list1
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [17]:
result_prod = arr_list1 * arr_list2
result_prod

array([  50,  200,  450,  800, 1250])

###### - Division

In [18]:
result_quotient = arr_list2 / arr_list1
result_quotient

array([2., 2., 2., 2., 2.])

#### Floor Division

In [19]:
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2], dtype=int32)

#### Modulo

In [20]:
result_mod = arr_list2 % arr_list1
result_mod

array([0, 0, 0, 0, 0], dtype=int32)

#### Numpy Subsetting

In [21]:
print(result_prod)
print(result_prod < 800)
print(result_prod[result_prod < 800])

[  50  200  450  800 1250]
[ True  True  True False False]
[ 50 200 450]


In [22]:
test_ndStrings = np.array(['Bob','Mark','Angelica','Barb'])
print(test_ndStrings == 'Bob')
print(test_ndStrings[0] == 'Bob')
# print(test_ndStrings[test_ndStrings[0] == 'B'])

# conditional check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


[ True False False False]
True


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [23]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step: convert lists into a Matrix
M = [aList, bList, cList]
print(M)
print(M[1][1])
print(type(M))
# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(ND_M)
ND_M

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
4
<class 'list'>
[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [24]:
# Syntax - Matrix[row,column] (row and column are 0-based index)

print(ND_M)
print(ND_M[1,1]) # second row, second column

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


#### Assigning Values in NDArrays

In [25]:
# Syntax - Matrix[row, column] = value

ND_M[1,1] = 10

print(ND_M)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]


#### Checking NDArray Type

In [26]:
# usind the .dtype attribute
nd_type = ND_M.dtype

print(nd_type)
nd_type

int32


dtype('int32')

#### .astype()

In [27]:
print(f"Before change: {ND_M.dtype}")

new_ND_M = ND_M.astype(np.float32)

print(f"New changed type: {new_ND_M.dtype}")

Before change: int32
New changed type: float32


In [28]:
print(ND_M)
print(new_ND_M)

[[ 0  1  2]
 [ 3 10  5]
 [ 6  7  8]]
[[ 0.  1.  2.]
 [ 3. 10.  5.]
 [ 6.  7.  8.]]


In [29]:
# Checking the Shape of the ND_M Numpy Array
# Using the method .shape


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [30]:
 # shape is always rows x columns
# Checking the Shape of the ND_M Numpy Array
# Using the .shape attribute

shape = new_ND_M.shape
print(shape)
print(type(shape))

(3, 3)
<class 'tuple'>


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [31]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column


print(new_ND_M.reshape((9, 1)))

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [10.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]]


In [32]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrix

In [34]:
"""
OUTPUT
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])
"""
x = np.arange(16).reshape((4,4))

#### Complex Indexing & Assinging

In [42]:
my_list = [1, 2, 3, 4, 5]
my_list[:]

[1, 2, 3, 4, 5]

In [63]:
# Refresh - Matrix[row(s), column(s)]

print('Setting Matrix')
M = np.zeros((6,6))
print('Before any assignment:')
print(M)

# Set every first element in each row to 1 (first column)
M[:, 0] = 1
print('\nAfter assigning 1 to first column:')
print(M)

# Set all elements in rows 3 to 5 to be 5
M[2:5, :] = 5
print('\nAfter assigning 5 to rows 3-5:')
print(M)


# Reset to 0s
print('Reset to Zero')
M = M * 0
print(M)

# Set the second and third column to be the number 2
M[:,1:3] = 2
print('\nAfter assigning 2 to columns two and three:')
print(M)

# Set every other row to be 100
M[::2 , :] = 100
print('\nAfter assigning 100 to every other row:')
print(M)

print('Reset to Zero')
M = M * 0
print(M)

# Create a vector to assign to the first row
x = np.arange(6)
M[0, :] = x
print('\nAfter assigning the vector to the first row:')
print(M)

Setting Matrix
Before any assignment:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

After assigning 1 to first column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]

After assigning 5 to rows 3-5:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [1. 0. 0. 0. 0. 0.]]
Reset to Zero
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

After assigning 2 to columns two and three:
[[0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]
 [0. 2. 2. 0. 0. 0.]]

After assigning 100 to every other row:
[[100. 100. 100. 100. 100. 100.]
 [  0.   2.   2.   0.   0.   0.]
 [100. 100. 100. 100. 100. 100.]
 [  0.   2.   2.   0.   0.   0.]
 [100. 100. 100. 100. 100. 

In [52]:
my_list = [i for i in range(100)]
my_list[::5]

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [71]:
M = np.ones((10, 4))

print(M)

v = np.arange(5)

print(v)

print(M.shape, v.shape)

new_M = M.reshape((8,5))* v
print(new_M)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 1 2 3 4]
(10, 4) (5,)
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [79]:
arr_list1 = np.array([5,10,15,20,25])
arr_list2 = np.array([10,20,30,40,50])
result_prod = arr_list1 * arr_list2
print(result_prod)
print(result_prod < 800)
print(np.where(result_prod < 800))


# Subset using np.where
print(result_prod[np.where(result_prod < 800)])

# Transform data
result_prod[np.where(result_prod % 100 == 50)] = 1000
print(result_prod)

[  50  200  450  800 1250]
[ True  True  True False False]
(array([0, 1, 2], dtype=int64),)
[ 50 200 450]
[1000  200 1000  800 1000]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [122]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.6752422385169765
Here is a random number between 0 and 1 Million: 334340.0520219714
Here are 5 random numbers between 0 and 10: [3.39934694 0.95637396 1.8887385  0.8910185  1.65580328]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[1.58548686 0.79349192 3.26421854]
 [8.12900068 9.51114874 2.27113318]
 [3.97575267 3.90326795 6.16665046]]


## Working With CSV's

#### Imports

In [124]:
import csv
from datetime import datetime

#### Reading a CSV

In [125]:
# Creating Function to open and read CSV data

def open_csv(filename, d=','):
    # define an empty list to store our data
    data = []
    
    # open up the file 
    with open(filename, encoding='utf-8') as marathon_data:
        # and create csv reader object
        reader = csv.reader(marathon_data, delimiter=d)
        
        # Iterate over each row in the csv and append it to the data list
        for row in reader:
            data.append(row)
    return data

marathon_data = open_csv('boston_marathon2017_edited.csv')


            

[['10K', '15K', '20K', '25K', '30K', '35K', '40K', '5K', 'Age', 'Bib', 'Overall Time in Seconds', 'Citizenship', 'Male Average Times', 'Females Average Times', 'City', 'Country', 'Division', 'Gender', 'Half', 'M/F', 'Name', 'Number of Records', 'Official Time', 'Overall', 'Pace', 'State'], ['12/30/1899 12:30:28 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:02:53 AM', '12/30/1899 12:15:25 AM', '24', '11', '7777', 'KEN', '7777', '', 'Keringet', 'KEN', '1', '1', '12/30/1899 1:04:35 AM', 'M', 'Kirui, Geoffrey', '1', '12/30/1899 2:09:37 AM', '1', '12/30/1899 12:04:57 AM', ''], ['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', 

#### Loading a CSV's Data 

In [215]:
FIELDS = ['Rank', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rank', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



# instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d=','):
    data = np.genfromtxt(filename, dtype=DATATYPES, delimiter=d, names=True, invalid_raise=False)
    return data
    
    
redsox17 = load_data('redsox_2017_hitting.txt')
redsox17
names = redsox17['Name']
print(names)
print(type(names))

hits = redsox17['H']
print(hits)
total_hits = sum(hits)
print(total_hits)


home_runs = redsox17['HR']
print(home_runs)
total_hrs = sum(home_runs)
print(total_hrs)


[b'Christian Vazquez' b'Mitch Moreland' b'Dustin Pedroia'
 b'Xander Bogaerts' b'Rafael Devers' b'Andrew Benintendi'
 b'Jackie Bradley Jr.' b'Mookie Betts' b'Hanley Ramirez' b'Sandy Leon'
 b'Chris Young' b'Deven Marrero' b'Eduardo Nunez' b'Brock Holt'
 b'Josh Rutledge' b'Pablo Sandoval' b'Sam Travis' b'Tzu-Wei Lin'
 b'Marco Hernandez' b'Rajai Davis' b'Steve Selsky' b'Blake Swihart'
 b"Chase d'Arnaud"]
<class 'numpy.ndarray'>
[ 94 125 119 156  63 155 118 166 120  61  57  36  53  28  24  21  20  15
  16   9   1   1   1]
1459
[ 5 22  7 10 10 20 17 24 23  7  7  4  8  0  0  4  0  0  0  0  0  0  0]
168


In [209]:
redsox18 = load_data('redsox_2018_hitting.txt')
redsox18

array([( 1, b'C', b'Sandy Leon', 29,  89, 288, 265,  30,  47, 12, 0,  5,  22,  1, 0, 15,  75, 0.177, 0.232, 0.279, 0.511,  37,  74,  6,  4, 3, 1,  0),
       ( 2, b'1B', b'Mitch Moreland', 32, 124, 459, 404,  57,  99, 23, 4, 15,  68,  2, 0, 50, 102, 0.245, 0.325, 0.433, 0.758, 102, 175, 12,  0, 0, 5,  2),
       ( 3, b'2B', b'Eduardo Nunez', 31, 127, 502, 480,  56, 127, 23, 3, 10,  44,  7, 2, 16,  69, 0.265, 0.289, 0.388, 0.677,  81, 186, 17,  2, 1, 3,  0),
       ( 4, b'SS', b'Xander Bogaerts', 25, 136, 580, 513,  72, 148, 45, 3, 23, 103,  8, 2, 55, 102, 0.288, 0.36 , 0.522, 0.883, 135, 268, 14,  6, 0, 6,  4),
       ( 5, b'3B', b'Rafael Devers', 21, 121, 490, 450,  59, 108, 24, 0, 21,  66,  5, 2, 38, 121, 0.24 , 0.298, 0.433, 0.731,  94, 195,  9,  0, 0, 2,  6),
       ( 6, b'LF', b'Andrew Benintendi', 23, 148, 661, 579, 103, 168, 41, 6, 16,  87, 21, 3, 71, 106, 0.29 , 0.366, 0.465, 0.83 , 123, 269,  9,  2, 2, 7,  1),
       ( 7, b'CF', b'Jackie Bradley Jr.', 28, 144, 535, 474,  76, 1

#### Summing the top 5 hitters for HR's

In [223]:
# find the top 5 hr hitters

# Step 1: Get all HR data into a variable
# Step 2: Get all the player names into a variable
# Step 3: Create a new empty list for decoded names
# Step 4: Loop through and decode each name and append to new list
# Step 5: Line up our player names with our hr data [(player, number_of_hr), (player2, number_of_hr),...]
# Step 6: Sort values based on number of home runs
# Step 7: Slice list to first 5

# Step 1
all_home_runs = redsox17['HR']
# print(all_home_runs)

# Step 2
all_players = redsox17['Name']
# print(all_players)

# Step 3
clean_names = []

# Step 4
for name in all_players:
    decoded_name = name.decode('utf-8')
    clean_names.append(decoded_name)
# print(clean_names)

# Step 5
zipped_values = list(zip(clean_names, all_home_runs))
# print(zipped_values)

# Step 6
sorted_home_runs = sorted(zipped_values, key=lambda player_tup: player_tup[1], reverse=True)
# print(sorted_home_runs)

# Step 7
top_5_home_run_hitters = sorted_home_runs[:5]
print(top_5_home_run_hitters)

[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>